package localengine

import (
	"context"
	"errors"
	"fmt"
	"log"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"

	"github.com/agodomen/Cli-Proxy-API-Management-Center/backend/internal/core/config"
	cliproxy "github.com/agodomen/Cli-Proxy-API-Management-Center/backend/sdk/cliproxy"
	cliproxyconfig "github.com/agodomen/Cli-Proxy-API-Management-Center/backend/sdk/config"
	"gopkg.in/yaml.v3"
)

// Runtime owns the CLIProxyAPI service embedded in the cpamc process.
type Runtime struct {
	service    *cliproxy.Service
	address    string
	configPath string
	mu         sync.RWMutex
	running    bool
	lastError  string
}

// Status describes the embedded runtime without exposing upstream internals.
type Status struct {
	Enabled    bool   `json:"enabled"`
	Running    bool   `json:"running"`
	Address    string `json:"address,omitempty"`
	ConfigPath string `json:"configPath,omitempty"`
	LastError  string `json:"lastError,omitempty"`
}

// New builds the embedded CLIProxyAPI runtime. A disabled configuration returns nil.
func New(cfg config.LocalEngineConfig, ingestor UsageEventIngestor) (*Runtime, error) {
	if !cfg.Enabled {
		return nil, nil
	}
	if strings.TrimSpace(cfg.ConfigPath) == "" {
		return nil, fmt.Errorf("local engine config path is required")
	}
	if cfg.Port <= 0 || cfg.Port > 65535 {
		return nil, fmt.Errorf("local engine port %d is invalid", cfg.Port)
	}
	if err := ensureConfigFile(cfg); err != nil {
		return nil, err
	}
	// Bootstrap management credentials from env only when config.yaml has no secret-key yet.
	// MANAGEMENT_PASSWORD is written as plaintext; LoadConfig below hashes and persists it.
	applied, err := injectManagementSecretFromEnv(cfg.ConfigPath)
	if err != nil {
		return nil, fmt.Errorf("inject management secret from env: %w", err)
	}
	logManagementPasswordBootstrapStatus(applied)

	upstreamConfig, err := cliproxyconfig.LoadConfig(cfg.ConfigPath)
	if err != nil {
		return nil, fmt.Errorf("load local engine config: %w", err)
	}
	upstreamConfig.Host = strings.TrimSpace(cfg.Host)
	upstreamConfig.Port = cfg.Port
	upstreamConfig.AuthDir, err = resolveAuthDir(upstreamConfig.AuthDir, filepath.Dir(cfg.ConfigPath))
	if err != nil {
		return nil, fmt.Errorf("resolve local engine auth directory: %w", err)
	}

	service, err := cliproxy.NewBuilder().
		WithConfig(upstreamConfig).
		WithConfigPath(cfg.ConfigPath).
		Build()
	if err != nil {
		return nil, fmt.Errorf("build local engine: %w", err)
	}
	if ingestor != nil {
		service.RegisterUsagePlugin(newUsagePlugin(ingestor))
	}

	return &Runtime{
		service:    service,
		address:    formatAddress(upstreamConfig.Host, upstreamConfig.Port),
		configPath: cfg.ConfigPath,
	}, nil
}

// Run starts the embedded server and blocks until cancellation or failure.
func (runtime *Runtime) Run(ctx context.Context) error {
	if runtime == nil || runtime.service == nil {
		return nil
	}
	runtime.setRunning(true, "")
	err := runtime.service.Run(ctx)
	if errors.Is(err, context.Canceled) {
		err = nil
	}
	if err != nil {
		runtime.setRunning(false, err.Error())
		return err
	}
	runtime.setRunning(false, "")
	return nil
}

// Shutdown gracefully stops the embedded server.
func (runtime *Runtime) Shutdown(ctx context.Context) error {
	if runtime == nil || runtime.service == nil {
		return nil
	}
	err := runtime.service.Shutdown(ctx)
	if err != nil {
		runtime.setRunning(false, err.Error())
		return err
	}
	runtime.setRunning(false, "")
	return nil
}

// Status returns a concurrency-safe runtime snapshot.
func (runtime *Runtime) Status() Status {
	if runtime == nil {
		return Status{}
	}
	runtime.mu.RLock()
	defer runtime.mu.RUnlock()
	return Status{
		Enabled:    true,
		Running:    runtime.running,
		Address:    runtime.address,
		ConfigPath: runtime.configPath,
		LastError:  runtime.lastError,
	}
}

func (runtime *Runtime) setRunning(running bool, lastError string) {
	runtime.mu.Lock()
	runtime.running = running
	runtime.lastError = lastError
	runtime.mu.Unlock()
}

func ensureConfigFile(cfg config.LocalEngineConfig) error {
	if _, err := os.Stat(cfg.ConfigPath); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("inspect local engine config: %w", err)
	}
	configDir := filepath.Dir(cfg.ConfigPath)
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return fmt.Errorf("create local engine config directory: %w", err)
	}
	authDir := filepath.Join(configDir, "auths")
	content := fmt.Sprintf(`# Generated by cpamc. Extend this file with CLIProxyAPI provider settings.
host: %s
port: %d
auth-dir: %s
api-keys: []
usage-statistics-enabled: true
remote-management:
  allow-remote: false
  secret-key: ""
plugins:
  enabled: false
`, strconv.Quote(strings.TrimSpace(cfg.Host)), cfg.Port, strconv.Quote(authDir))
	if err := os.WriteFile(cfg.ConfigPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("create local engine config: %w", err)
	}
	return nil
}

// logManagementPasswordBootstrapStatus notes whether MANAGEMENT_PASSWORD was
// applied into config.yaml. The plaintext value itself is logged once by cmd/cpamc.
func logManagementPasswordBootstrapStatus(bootstrapped bool) {
	envPassword := strings.TrimSpace(os.Getenv("MANAGEMENT_PASSWORD"))
	if envPassword == "" {
		return
	}
	if bootstrapped {
		log.Printf("remote-management.secret-key bootstrapped from MANAGEMENT_PASSWORD")
		return
	}
	log.Printf("MANAGEMENT_PASSWORD present but secret-key already set; env not applied")
}

// injectManagementSecretFromEnv bootstraps remote-management.secret-key from
// MANAGEMENT_PASSWORD when the key is still empty in config.yaml.
//
// Flow:
//  1. If config.yaml already has a non-empty secret-key, leave it alone.
//  2. Else if MANAGEMENT_PASSWORD is set, write it (plaintext) into secret-key.
//     LoadConfig later hashes it with bcrypt and persists the hash.
//  3. When injecting, also set allow-remote from MANAGEMENT_REMOTE:
//     "1"/"true"/"yes"/"on" → true, otherwise false.
//
// Once a secret-key exists in config.yaml, subsequent restarts ignore both env
// vars so operators can rotate credentials by editing the file (or via the UI)
// without env overrides silently winning.
//
// The bool return is true when the env password was written into config.yaml.
func injectManagementSecretFromEnv(configPath string) (bool, error) {
	envPassword := strings.TrimSpace(os.Getenv("MANAGEMENT_PASSWORD"))
	if envPassword == "" {
		return false, nil
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		return false, fmt.Errorf("read local engine config for secret injection: %w", err)
	}

	var root yaml.Node
	if err = yaml.Unmarshal(data, &root); err != nil {
		return false, fmt.Errorf("parse local engine config for secret injection: %w", err)
	}
	if root.Kind != yaml.DocumentNode || len(root.Content) == 0 {
		return false, fmt.Errorf("invalid yaml document structure in %s", configPath)
	}

	// Skip when secret-key is already set (plaintext or bcrypt hash).
	if existing := nestedScalarValue(root.Content[0], "remote-management", "secret-key"); strings.TrimSpace(existing) != "" {
		return false, nil
	}

	if err = setNestedScalar(&root, []string{"remote-management", "secret-key"}, envPassword); err != nil {
		return false, fmt.Errorf("set remote-management.secret-key: %w", err)
	}

	allowRemote := "false"
	if envBoolTruthy(os.Getenv("MANAGEMENT_REMOTE")) {
		allowRemote = "true"
	}
	if err = setNestedScalar(&root, []string{"remote-management", "allow-remote"}, allowRemote); err != nil {
		return false, fmt.Errorf("set remote-management.allow-remote: %w", err)
	}

	// Preserve file mode (ensureConfigFile writes 0o600).
	mode := os.FileMode(0o600)
	if info, statErr := os.Stat(configPath); statErr == nil {
		mode = info.Mode().Perm()
	}

	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err = enc.Encode(&root); err != nil {
		_ = enc.Close()
		return false, fmt.Errorf("encode local engine config after secret injection: %w", err)
	}
	if err = enc.Close(); err != nil {
		return false, fmt.Errorf("close yaml encoder after secret injection: %w", err)
	}
	if err = os.WriteFile(configPath, []byte(buf.String()), mode); err != nil {
		return false, fmt.Errorf("write local engine config after secret injection: %w", err)
	}
	return true, nil
}


// nestedScalarValue walks mapping nodes following keys and returns the final
// scalar value, or "" if any key is missing / not a scalar.
func nestedScalarValue(node *yaml.Node, keys ...string) string {
	current := node
	for _, key := range keys {
		if current == nil || current.Kind != yaml.MappingNode {
			return ""
		}
		var next *yaml.Node
		for i := 0; i+1 < len(current.Content); i += 2 {
			if current.Content[i].Value == key {
				next = current.Content[i+1]
				break
			}
		}
		if next == nil {
			return ""
		}
		current = next
	}
	if current == nil || current.Kind != yaml.ScalarNode {
		return ""
	}
	return current.Value
}

// setNestedScalar sets (or creates) a nested scalar under a YAML document root.
func setNestedScalar(root *yaml.Node, path []string, value string) error {
	if root == nil || root.Kind != yaml.DocumentNode || len(root.Content) == 0 {
		return fmt.Errorf("invalid yaml document structure")
	}
	node := root.Content[0]
	for i, key := range path {
		if node.Kind != yaml.MappingNode {
			node.Kind = yaml.MappingNode
			node.Tag = "!!map"
			node.Content = nil
		}
		var next *yaml.Node
		for j := 0; j+1 < len(node.Content); j += 2 {
			if node.Content[j].Value == key {
				next = node.Content[j+1]
				break
			}
		}
		if next == nil {
			keyNode := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}
			next = &yaml.Node{}
			node.Content = append(node.Content, keyNode, next)
		}
		if i == len(path)-1 {
			next.Kind = yaml.ScalarNode
			next.Tag = "!!str"
			next.Value = value
			// Keep allow-remote as a real bool so yaml consumers see !!bool.
			if path[i] == "allow-remote" && (value == "true" || value == "false") {
				next.Tag = "!!bool"
			}
			return nil
		}
		if next.Kind != yaml.MappingNode {
			next.Kind = yaml.MappingNode
			next.Tag = "!!map"
			next.Content = nil
		}
		node = next
	}
	return nil
}

func envBoolTruthy(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func resolveAuthDir(authDir string, configDir string) (string, error) {
	authDir = strings.TrimSpace(authDir)
	if authDir == "" {
		return filepath.Join(configDir, "auths"), nil
	}
	if authDir == "~" || strings.HasPrefix(authDir, "~/") || strings.HasPrefix(authDir, `~\`) {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		remainder := strings.TrimLeft(strings.TrimPrefix(authDir, "~"), `/\`)
		return filepath.Join(homeDir, filepath.FromSlash(strings.ReplaceAll(remainder, `\`, "/"))), nil
	}
	if filepath.IsAbs(authDir) {
		return filepath.Clean(authDir), nil
	}
	return filepath.Clean(filepath.Join(configDir, authDir)), nil
}

func formatAddress(host string, port int) string {
	host = strings.TrimSpace(host)
	if host == "" {
		host = "0.0.0.0"
	}
	return net.JoinHostPort(host, strconv.Itoa(port))
}
